### ISSUE TITLE
Form password matching, does not work anymore!

### ISSUE THREAD

**Issue by EdgeCastMedia** [nuxt-community/vuetify-module#31]
When adding form rules the rules for matching password use to work with the previous vuetify that came pre installed in Nuxt. However I think this module is WAY better as far as loading time but the same rules now break my app. Here is my password word fields...

 <v-text-field
            v-model="password"
            :rules="passwordRules"
            :append-icon="show ? 'visibility_off' : 'visibility'"
            :type="show ? 'text' : 'password'"
            label="Password"
            placeholder="Enter password"
            required
            tile
            @click:append="show = !show"
          />
          <v-text-field
            v-model="passwordConfirmation"
            :rules="passwordRules"
            :append-icon="show ? 'visibility_off' : 'visibility'"
            :type="show ? 'text' : 'password'"
            label="Password"
            placeholder="Confirm Password"
            required
            tile
            @click:append="show = !show"
          />

Here is my rules: 
data: () => ({
    value: null,
    show: false,
    dialog: true,
    title: 'Enter new password',
    update: '  Reset Password',
    isFormValid: true,
    password: '',
    passwordConfirmation: '',
    passwordRules: [
      password => !!password || 'Password is required',
      password => password.length >= 6 || 'Password must be at least 6 characters',
      confirmation => confirmation === this.password || 'Passwords must match'
    ]
  })
 
these two work as expected: 
 password => !!password || 'Password is required',
  password => password.length >= 6 || 'Password must be at least 6 characters',
 

this works works fine in previous installs:
    confirmation => confirmation === this.password || 'Passwords must match'

But now errors. console says:

TypeError: Cannot read property 'password' of undefined
    at passwordRules (_id.1c0d67116b3b8744ad5f.hot-update.js:120)
    at VueComponent.validate (vendors.app.js:89420)
    at VueComponent.beforeMount (vendors.app.js:89389)
    at invokeWithErrorHandling (commons.app.js:11680)
    at callHook (commons.app.js:14034)
    at mountComponent (commons.app.js:13858)
    at VueComponent.push../node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount (commons.app.js:18226)
    at init (commons.app.js:12942)
    at createComponent (commons.app.js:15789)
    at createElm (commons.app.js:15736) 

How to get this to work again??

**Comment by EdgeCastMedia** [comment]
FIXED

It seems to be the way you write your data syntax.

Doesn't work when: 
data: () => ({}) 
  
Does work:
data(){
   return {

   }
}

**Comment by aldarund** [comment]
Its nothing to do with with this module

**Comment by peppeg85** [comment]
i have the same issue

**Comment by likdy** [comment]
I'm try with this syntax
data() {
     return {
     }
}
but still not work. Have any solution everyone?

**Comment by peppeg85** [comment]
@likdy report the error to understand what is your problem
